name: platformio build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore: [ "*.md" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "*.md" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        AWS_IOT_SHADOW_SUPPORT_DELTA: [ 0, 1 ]
        AWS_IOT_SHADOW_SUPPORT_DELETE: [ 0, 1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.8

      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Dummy certs
        run: |
          touch example/main/certs/certificate.pem.crt
          touch example/main/certs/private.pem.key

      - name: Check
        run: platformio check -d example
        env:
          PLATFORMIO_BUILD_FLAGS: >-
            -D AWS_IOT_SHADOW_SUPPORT_DELTA=${{ matrix.AWS_IOT_SHADOW_SUPPORT_DELTA }}
            -D AWS_IOT_SHADOW_SUPPORT_DELETE=${{ matrix.AWS_IOT_SHADOW_SUPPORT_DELETE }}

      - name: Build
        run: platformio run -d example
        env:
          PLATFORMIO_BUILD_FLAGS: >-
            -D AWS_IOT_SHADOW_SUPPORT_DELTA=${{ matrix.AWS_IOT_SHADOW_SUPPORT_DELTA }}
            -D AWS_IOT_SHADOW_SUPPORT_DELETE=${{ matrix.AWS_IOT_SHADOW_SUPPORT_DELETE }}
