name: platformio build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore: [ "*.md" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "*.md" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Dummy certs
        run: |
          touch example/main/certs/certificate.pem.crt
          touch example/main/certs/private.pem.key

      - name: Check
        run: platformio check -d example

      - name: Build
        run: platformio run -d example
